### ISSUE TITLE
MissingAuthenticationToken: Request is missing Authentication Token

### ISSUE THREAD

**Issue by bpotaczek** [cert-manager/aws-privateca-issuer#40] opened 2021-07-20 19:03 UTC
I wanted to upgrade to the latest v0.3.0 but when I tried I noticed I started seeing exceptions in the logs.

We are using AWS IAM roles as annotations on the serviceAccount to handle the authorization. This works in v0.2.1 and I've looked through the code but I see no differences between 0.2.1 and 0.3.0 that would cause this. 

```
{"level":"error","ts":1626803861.6337998,"logger":"controllers.GenericIssuer","msg":"failed to sts.GetCallerIdentity","genericissuer":"/aws-issuer","error":"operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: dd011a20-5b5f-4191-9996-cd709af162f9, api error MissingAuthenticationToken: Request is missing Authentication Token","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/cert-manager/aws-privateca-issuer/pkg/controllers.(*GenericIssuerReconciler).Reconcile\n\t/workspace/pkg/controllers/genericissuer_controller.go:122\ngithub.com/cert-manager/aws-privateca-issuer/pkg/controllers.(*AWSPCAClusterIssuerReconciler).Reconcile\n\t/workspace/pkg/controllers/awspcaclusterissuer_controller.go:57\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
{"level":"error","ts":1626803861.6339357,"logger":"controller-runtime.manager.controller.awspcaclusterissuer","msg":"Reconciler error","reconciler group":"awspca.cert-manager.io","reconciler kind":"AWSPCAClusterIssuer","name":"aws-issuer","namespace":"","error":"operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: dd011a20-5b5f-4191-9996-cd709af162f9, api error MissingAuthenticationToken: Request is missing Authentication Token","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:302\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
```

**Comment by jonathanio** [comment] 2021-07-23 09:04
I'm seeing the same issue myself, although in this case, it's a brand new installation, not an existing upgrade. Like yourself, I'm also using AWS IAM Role annotations on the ServiceAccount to provide the permissions to the Pod.

**Comment by eperdeme** [comment] 2021-07-23 14:30
Same issue here.

**Comment by divyansh-gupta** [comment] 2021-07-23 18:18
I am taking a look at this issue.

**Comment by jonathanio** [comment] 2021-07-23 18:23
Thanks. I can confirm that downgrading to 0.2.1 worked for me too.

**Comment by divyansh-gupta** [comment] 2021-07-23 18:29
@bpotaczek can you please provide steps to re-produce the issue?

**Comment by bpotaczek** [comment] 2021-07-26 20:12
To reproduce I either start with a fresh cluster or remove istio, istio-csr, aws-pca-issuer charts plus delete all Certificates, CertificateRequests and AWSPCAClusterIssuers. 

Then I install the aws-pca-issuer with my values.yaml file which has the serviceAccount create and custom annotation for the IRSA authentication.

```
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXXXX:role/aws-pca-issuer-k8s-aws-pca-issuer-dev
```

I start following the pca issuer logs.

After the pod is fully running and listening I create an AWSPCAClusterIssuer. 
```
apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAClusterIssuer
metadata:
  name: aws-issuer
spec:
  region: us-east-1
  arn: arn:aws:acm-pca:us-east-1:XXXXXXXXXXXX:certificate-authority/00000000-0000-0000-0000-000000000000
```

I have tried using an ACM in the same account as well as a RAM share ACM and both fail.

**Comment by bpotaczek** [comment] 2021-07-26 20:33
@divyansh-gupta I have been working on a fix for it. To get it to work I had to redo how the aws config is loaded. I put together a branch and draft PR here but I am very new to Go so I am not sure if I have something wrong. Just wanted to get something for you to see and/or use to get a fix in place. I tested this and this code works for me when using the steps above. I was even able to get istio-csr and istiod working with it.

https://github.com/cert-manager/aws-privateca-issuer/pull/41

**Comment by divyansh-gupta** [comment] 2021-07-27 13:58
@bpotaczek Thanks for the steps to reproduce - I was able to reproduce the issue using an instance profile, running on an EC2 instance.

I am also testing your PR, thank you putting that out.

**Comment by divyansh-gupta** [comment] 2021-07-29 18:20
Hey @bpotaczek, thanks for your work on that fix. We have merged it in: https://github.com/cert-manager/aws-privateca-issuer/pull/41

We will be cutting a new release soon. Closing, please re-open if there are any other comments.

**Closed by divyansh-gupta** 2021-07-29 18:20 UTC
Labels: bug

**Comment by joaosilva15** [comment] 2021-08-18 16:40
Hey 👋 Something which seems related to this issue. With version 0.3.1 when I try to use IAM and eks service account I get access denied to the resource. Downgrading the version to v0.2.1 works fine and I'm able to issue certificates

**Comment by paramsethi** [comment] 2021-08-18 17:35
@joaosilva15 Thanks for reaching out.

With 0.3.1 release, you need updated IAM policy as called out in the README file:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "awspcaissuer",
      "Action": [
        "acm-pca:DescribeCertificateAuthority",
        "acm-pca:GetCertificate",
        "acm-pca:IssueCertificate"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:acm-pca:<region>:<account_id>:certificate-authority/<resource_id>"
    }
  ]
}

Can you please verify that IAM principal has the right policy attached for certificate issuance? Thanks!

**Comment by joaosilva15** [comment] 2021-08-18 21:17
Hey. Yes the policies were attached to the role and I could use the role with the cli. Downgrading the app to 0.2.1 fixed the issue and I'm able to issue the certificate.
A thing that also was strange was that the role did not changed it's last used time in the console while the issuer was trying to issue the cert

Regarding our setup (just to clear all possibilities), we have a subordinate CA shared with the account of the issuer and we want to issue certs for that account.

Thank you :)

**Comment by divyansh-gupta** [comment] 2021-08-19 15:59
Hi @joaosilva15, could you please provide steps to reproduce? I was not able to reproduce. Please check out https://github.com/cert-manager/aws-privateca-issuer/issues/48 as well, is your issue related to `fsGroup`?

**Comment by joaosilva15** [comment] 2021-08-23 14:21
Hi. So our setup is

We have an aws account with only acm pca. There we have a root CA and we create a subordinate CA from the root. This subordinate CA is then shared with multiple accounts.

We have then in each account where the subordinate was shared an eks cluster with certmanager and aws pca issuer running. The containers for pca issuer are running with a service account that is associate with a role with the policy 
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "awspcaissuer",
      "Action": [
        "acm-pca:GetCertificate",
        "acm-pca:GetCertificateAuthorityCertificate",
        "acm-pca:IssueCertificate",
        "acm-pca:DescribeCertificateAuthority"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:acm-pca:eu-west-1:<account>:certificate-authority/*"
    }
  ]
}
```

I was running around with version 0.3.1 and getting error like `{"level":"error","ts":1629727036.659929,"logger":"controllers.CertificateRequest","msg":"failed to request certificate from PCA","certificaterequest":"default/test-xhzft","error":"operation error ACM PCA: IssueCertificate, https response error StatusCode: 400, RequestID: fd99a19a-011a-4301-a426-6676fd59ca42, api error AccessDeniedException: User: arn:aws:sts::<test:account>:assumed-role/<test-role> is not authorized to perform: acm-pca:IssueCertificate on resource: arn:aws:acm-pca:eu-west-1:<ca-account>:certificate-authority/<ca-shared>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\ngithub.com/cert-manager/aws-privateca-issuer/pkg/controllers.(*CertificateRequestReconciler).Reconcile\n\t/workspace/pkg/controllers/certificaterequest_controller.go:171\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}`

I downgraded the version to 0.2.1 and everything works so I think it should be something related with this fix? Not sure though, if you want I can open a new issue.

Regarding your comment, the issue is not that the container cannot fetch the token, it knows what is his role and region, but to clear doubts I added the fsGroup to the container and the issue still occurs.

**Comment by joaosilva15** [comment] 2021-08-24 10:14
I believe the issue that I'm having is https://github.com/cert-manager/aws-privateca-issuer/issues/50 . I will follow up there. Thanks!

**Comment by youwalther65** [comment] 2021-11-07 14:54
I used the Helm chart version "0.1.2" a minute ago which belongs to "image: ghcr.io/jniebuhr/aws-pca-issuer:v0.3.1" which should have fixed the IRSA issue but still get the following error:
{"level":"error","ts":1636296506.7310438,"logger":"controller-runtime.manager.controller.awspcaclusterissuer","msg":"Reconciler error","reconciler group":"awspca.cert-manager.io","reconciler kind":"AWSPCAClusterIssuer","name":"tf-eks-root-ca","namespace":"","error":"operation error STS: GetCallerIdentity, failed to sign request: failed to retrieve credentials: failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, https response error StatusCode: 403, RequestID: ca384609-e126-4d6c-bcf0-6e8b0bd230cb, api error AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:302\nsigs.k8s.io/controller-runtime/pkg/internal/controller.

The SA is properly annotated an the role policy is correct as well! pod has projected volume with credentials. What goes wrong here?
