### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by george-paw** [cert-manager/aws-privateca-issuer#272] opened 2023-07-14 05:08 UTC
### Describe the expected outcome

aws-pca-issuer pod supposed to be running in Kubernetes

### Describe the actual outcome

Recently updated to EKS 1.27 and now the pod is constantly crashing

```
NAME                                                   READY   STATUS             RESTARTS      AGE
aws-pca-issuer-aws-privateca-issuer-56f76cf7dc-xj4s4   0/1     Error     4 (54s ago)   106s
```

`kubectl logs -f aws-pca-issuer-aws-privateca-issuer-56f76cf7dc-xj4s4`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x137e050]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:114
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00004bd70, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:95 +0x6f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc00004ab58, 0x15}, {0xc0004045c0, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/aggregated_discovery.go:49 +0x125
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0xc0000becb0?)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:328 +0x3de
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0x46b2e7?)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:203 +0x65
k8s.io/client-go/discovery.ServerGroupsAndResources({0x1d35df8, 0xc00037e7b0})
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:413 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:376 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc00020f0f8)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:651 +0x71
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
	/go/pkg/mod/k8s.io/client-go@v0.26.3/discovery/discovery_client.go:375 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x1d35df8?, 0xc00037e7b0?})
	/go/pkg/mod/k8s.io/client-go@v0.26.3/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:94 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc0004235d8?, {0x0, 0x0, 0x14ba94e?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/client/apiutil/dynamicrestmapper.go:110 +0x182
sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0x1a2e8a0?)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/cluster/cluster.go:217 +0x25
sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc000358240, {0xc000423a98, 0x1, 0x0?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/cluster/cluster.go:159 +0x18d
sigs.k8s.io/controller-runtime/pkg/manager.New(_, {0xc0001f4310, 0x0, 0x0, {{0x1d325c8, 0xc000369580}, 0x0}, 0x1, {0x0, 0x0}, ...})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/manager/manager.go:351 +0xf9
main.main()
	/workspace/main.go:76 +0x379
```

### Steps to reproduce

Followed the readme instructions

```
helm repo add awspca https://cert-manager.github.io/aws-privateca-issuer
helm install awspca/aws-privateca-issuer --generate-name
```

### Version

aws-privateca-issuer: 1.2.5
EKS Cluster 1.27

### Have you tried the following?

- [X] Check the [Troubleshooting section](../#troubleshooting)
- [X] Search open [issues](https://github.com/cert-manager/aws-privateca-issuer/issues)

### Category

Other

### Severity

Severity 1

**Comment by bmsiegel** [comment] 2023-07-14 05:21
Thanks for opening the bug. I am working on trying to reproduce.

**Comment by bmsiegel** [comment] 2023-07-14 06:20
I'm not seeing the error, currently I'm receiving a hanging pod in the pending state

**Comment by bmsiegel** [comment] 2023-07-14 06:46
I completed the setup and my cluster is running. Do you have more specific steps for your setup? Here is my output from `kubectl get pods -A`

```
NAMESPACE        NAME                                               READY   STATUS             RESTARTS      AGE
aws-pca-issuer   aws-privateca-issuer-1689317053-5b575c585b-rd69z   1/1     Running            0             92s
kube-system      aws-node-7z9s5                                     1/1     Running            0             4m3s
kube-system      aws-node-gg6lb                                     1/1     Running            0             4m12s
kube-system      coredns-647484dc8b-d5sdf                           1/1     Running            0             11m
kube-system      coredns-647484dc8b-njlmj                           1/1     Running            0             11m
kube-system      kube-proxy-sxnh6                                   1/1     Running            0             4m3s
kube-system      kube-proxy-x6s5l                                   1/1     Running            0             4m12s
```

**Comment by george-paw** [comment] 2023-07-14 08:32
No specific steps. I just create a new namespace in my EKS 1.27 cluster and that's the only app running.

Here's the pod yaml

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-14T08:28:41Z"
  generateName: aws-privateca-issuer-1689323313-65697795d4-
  labels:
    app.kubernetes.io/instance: aws-privateca-issuer-1689323313
    app.kubernetes.io/name: aws-privateca-issuer
    pod-template-hash: 65697795d4
  name: aws-privateca-issuer-1689323313-65697795d4-v5kzw
  namespace: please-delete-2
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: aws-privateca-issuer-1689323313-65697795d4
    uid: 454fc14e-9923-49ae-a7c1-ffd476ed90bc
  resourceVersion: "219952267"
  uid: 4eb3f435-129f-4e03-837e-206bb823f4a8
spec:
  containers:
  - args:
    - --leader-elect
    command:
    - /manager
    image: public.ecr.aws/k1n1h4h4/cert-manager-aws-privateca-issuer:v1.2.5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 1
    name: aws-privateca-issuer
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4zhjj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: foobar.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 100
  priorityClassName: default-priority
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 65532
  serviceAccount: aws-privateca-issuer-1689323313
  serviceAccountName: aws-privateca-issuer-1689323313
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-4zhjj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-07-14T08:28:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-07-14T08:28:41Z"
    message: 'containers with unready status: [aws-privateca-issuer]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-07-14T08:28:41Z"
    message: 'containers with unready status: [aws-privateca-issuer]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-07-14T08:28:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://faa64c647136bd5429f0158405da7c81c74b282ab8eee14d80b4f6b3167156b6
    image: public.ecr.aws/k1n1h4h4/cert-manager-aws-privateca-issuer:v1.2.5
    imageID: public.ecr.aws/k1n1h4h4/cert-manager-aws-privateca-issuer@sha256:6adac539185c8def627213d710e3e564be7012652bca4c6792ac9b795eb4f4f0
    lastState:
      terminated:
        containerID: containerd://faa64c647136bd5429f0158405da7c81c74b282ab8eee14d80b4f6b3167156b6
        exitCode: 2
        finishedAt: "2023-07-14T08:30:20Z"
        reason: Error
        startedAt: "2023-07-14T08:30:20Z"
    name: aws-privateca-issuer
    ready: false
    restartCount: 4
    started: false
    state:
      waiting:
        message: back-off 1m20s restarting failed container=aws-privateca-issuer pod=aws-privateca-issuer-1689323313-65697795d4-v5kzw_please-delete-2(4eb3f435-129f-4e03-837e-206bb823f4a8)
        reason: CrashLoopBackOff
  hostIP: 10.202.73.139
  phase: Running
  podIP: 10.202.78.8
  podIPs:
  - ip: 10.202.78.8
  qosClass: BestEffort
  startTime: "2023-07-14T08:28:41Z"
  ```

**Comment by bmsiegel** [comment] 2023-07-14 11:52
So I did some research, and it looks like our api-resource is not returning a group, and the version of client-go we're using is not tolerant of a missing group. Going to look and see if this is a quick fix. https://github.com/kubernetes/kubernetes/pull/116603

**Comment by bmsiegel** [comment] 2023-07-14 11:54
Looks like if we update our client-go version to 0.26.4 it should fix it. Let me get a PR out and run some testing on it

**Comment by bmsiegel** [comment] 2023-07-14 12:36
I'm still struggling with reproducing this issue, so let me send you the exact steps I ran to get this working and see where we deviate. If I'm able to reproduce the issue it will make it a lot smoother to root cause.

```
eksctl create cluster --name acm-pca-lab --version 1.27 --nodegroup-name acm-pca-nlb-lab-workers --node-type t2.medium --nodes 2 --region us-east-2
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
kubectl create namespace aws-pca-issuer
helm repo add awspca https://cert-manager.github.io/aws-privateca-issuer
helm repo update
helm install awspca/aws-privateca-issuer  --generate-name --namespace aws-pca-issuer
```

**Comment by bmsiegel** [comment] 2024-02-21 21:30
Going to close this issue due to non-response. Please reopen if you're experiencing the same issue or have more to add!

**Closed by bmsiegel** 2024-02-21 21:30 UTC
Labels: bug
